services:
  - type: web
    name: basic-laravel-render-app-nutthakit.onrender.com
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
      php artisan db:seed --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
      php artisan optimize:clear
      npm install
      npm run build
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    plan: free
    autoDeploy: true